version: '3.8'

services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_standalone
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW_DB_URI}
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW__WEBSERVER__WEB_SERVER_URL=http://localhost:8080
      - AIRFLOW__LOGGING__REMOTE_LOGGING=False
      - AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT=8793            
    depends_on:
      - airflow_metadata
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
    networks:
      - airflow-networks

  airflow_metadata:
    image: postgres:latest
    container_name: airflow_metadata
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB_NAME}
    ports:
      - 5435:5432
    volumes:
      - airflow_metadata:/var/lib/postgresql/data
    networks:
      - airflow-networks

  warehouse_pacflight:
    image: postgres:latest
    container_name: warehouse_pacflight
    environment:
      POSTGRES_USER: ${WAREHOUSE_DB_USER}
      POSTGRES_PASSWORD: ${WAREHOUSE_DB_PASSWORD}
      POSTGRES_DB: ${WAREHOUSE_DB_NAME}
    ports:
      - 5434:5432
    networks:
      - airflow-networks
    volumes:
      - ./data/warehouse:/docker-entrypoint-initdb.d
      - warehouse_pacflight:/var/lib/postgresql/data

  pacflight_db:
    image: postgres:latest
    container_name: pacflight_db
    environment:
      POSTGRES_USER: ${PACFLIGHT_DB_USER}
      POSTGRES_PASSWORD: ${PACFLIGHT_DB_PASSWORD}
      POSTGRES_DB: ${PACFLIGHT_DB_NAME}
    ports:
      - 5436:5432
    networks:
      - airflow-networks
    volumes:
      - ./data/source:/docker-entrypoint-initdb.d
      - pacflight_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    container_name: minio
    hostname: minio
    restart: always
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    healthcheck: # make sure minio running
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - airflow-networks

  bucket_creator:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy # make sure minio running
    entrypoint: >
      /bin/sh -c "
        sleep 10;
        mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
        mc mb local/extracted-data || echo 'Bucket already exists';
        exit 0;
      "
    networks:
      - airflow-networks

volumes:
  airflow_metadata:
    driver: local
    name: airflow_metadata

  pacflight_data:
    driver: local
    name: pacflight_data

  minio-data:
    driver: local
    name: minio-data

  warehouse_pacflight:
    driver: local
    name: warehouse_pacflight

networks:
  airflow-networks:
    driver: bridge
    name: airflow-networks